name: GithubActions- TestRun

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Run Python Script
      run: python RunThis.py


